"use client";

import { CategoryGrid, ProductGrid } from "@/components/products/catalog";
import Link from "next/link";
import { ArrowRight, BadgeCheck, ShieldCheck, Sparkles, Truck, Undo2 } from "lucide-react";
import { useQuery } from "@tanstack/react-query";
import { getCategories, getProducts } from "@/services/catalog";
import { ProductSkeleton } from "@/components/ui/product-skeleton";
import { ErrorState } from "@/components/ui/primitives";

export default function Home() {
  const categories = useQuery({ queryKey: ["categories"], queryFn: getCategories });
  const products = useQuery({ queryKey: ["products", "featured"], queryFn: () => getProducts({ sort: "popularity", limit: "8" }) });
  return <>
    <section className="hero overflow-hidden text-white"><div className="shell relative grid gap-10 py-16 lg:grid-cols-[1.05fr_.95fr] lg:py-24">
      <div className="relative z-10 flex flex-col justify-center"><p className="inline-flex w-fit items-center gap-2 rounded-full border border-white/15 bg-white/10 px-3 py-1.5 text-[11px] font-bold uppercase tracking-[.14em] text-lime-200"><Sparkles size={14} /> Curated, not crowded</p><h1 className="mt-6 max-w-xl text-5xl font-semibold tracking-[-.06em] sm:text-7xl">Things worth<br /><em className="font-serif font-normal text-lime-300">keeping close.</em></h1><p className="mt-6 max-w-lg text-lg leading-8 text-slate-300">A lively marketplace for independent makers, useful objects, and discoveries that feel like you found them first.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/products" className="btn bg-lime-300 text-slate-950 hover:bg-lime-200">Explore the drop <ArrowRight size={17} /></Link><Link href="/categories" className="btn border border-white/20 bg-white/5 text-white hover:bg-white/10">Browse categories</Link></div><div className="mt-12 flex gap-7 text-sm text-slate-300"><span><b className="block text-2xl text-white">24h</b>dispatch</span><span><b className="block text-2xl text-white">4.9/5</b>community love</span><span><b className="block text-2xl text-white">New</b>every week</span></div></div>
      <div className="relative z-10 min-h-[370px] overflow-hidden rounded-[2.5rem] border border-white/15 bg-[#202c3f]"><span className="hero-orb hero-orb--one" /><span className="hero-orb hero-orb--two" /><span className="hero-orb hero-orb--three" /><div className="hero-tile absolute left-7 top-9 w-52 rounded-3xl p-5 text-slate-900 sm:left-10 sm:top-12"><BadgeCheck className="text-emerald-700" size={21} /><p className="mt-7 text-xs font-bold uppercase tracking-widest text-slate-500">This week&apos;s find</p><p className="mt-1 font-serif text-3xl leading-8">Soft utility<br />for daily life.</p></div><div className="absolute bottom-8 right-7 rounded-full border border-white/20 bg-slate-950/60 px-4 py-2 text-xs font-bold backdrop-blur">● Live from independent sellers</div></div>
    </div></section>
    <section className="shell py-16"><div className="section-heading"><div><p className="eyebrow">Browse with ease</p><h2>Find your corner</h2></div><Link href="/categories" className="text-link">All categories <ArrowRight size={16} /></Link></div>{categories.isError ? <ErrorState onRetry={() => categories.refetch()} /> : categories.data?.length ? <CategoryGrid categories={categories.data} /> : <p className="text-slate-500">Categories will appear here once the store is stocked.</p>}</section>
    <section className="bg-[#e9eee2] py-16"><div className="shell"><div className="section-heading"><div><p className="eyebrow">Made to be used</p><h2>Popular right now</h2></div><Link href="/products?sort=popularity" className="text-link">View all <ArrowRight size={16} /></Link></div>{products.isLoading ? <div className="grid grid-cols-2 gap-4 sm:grid-cols-4">{Array.from({ length: 4 }, (_, index) => <ProductSkeleton key={index} />)}</div> : products.data?.products.length ? <ProductGrid products={products.data.products} /> : <p className="text-slate-500">No products are live yet.</p>}</div></section>
    <section className="shell py-16"><div className="grid overflow-hidden rounded-[2.5rem] bg-[#ffb57f] text-slate-950 md:grid-cols-2"><div className="p-9 sm:p-14"><p className="eyebrow text-orange-900">A little more for less</p><h2 className="mt-4 font-serif text-4xl">Find pieces that fit your budget.</h2><p className="mt-5 text-slate-700">Sort the live catalogue by price and shop active offers with availability confirmed by the store.</p><Link className="btn mt-8 bg-slate-950 text-white" href="/products?sort=price_asc">Shop by price</Link></div><div className="min-h-64 bg-[radial-gradient(circle_at_35%_40%,#dcff86_0,transparent_24%),radial-gradient(circle_at_70%_64%,#ff7548_0,transparent_25%),#1b2739]" /></div></section>
    <section className="shell grid gap-6 border-t border-stone-200 py-10 sm:grid-cols-3">{[[Truck, "Thoughtful delivery", "Free delivery on qualifying orders."], [Undo2, "Easy returns", "Fourteen days to change your mind."], [ShieldCheck, "Made to last", "Pieces selected for real life."]].map(([Icon, title, copy]) => { const Item = Icon as typeof Truck; return <div key={String(title)} className="flex gap-4"><Item className="mt-1 text-amber-700" size={21} /><div><h3 className="font-medium">{String(title)}</h3><p className="mt-1 text-sm text-slate-500">{String(copy)}</p></div></div>; })}</section>
  </>;
}
