"use client";

import Link from "next/link";
import { ArrowRight, BadgeCheck, Boxes, ShieldCheck, Sparkles, Truck, Undo2 } from "lucide-react";
import { useQuery } from "@tanstack/react-query";
import { getCategories, getProducts } from "@/services/catalog";
import { CategoryGrid, ProductGrid } from "@/components/products/catalog";
import { ProductSkeleton } from "@/components/ui/product-skeleton";
import { ErrorState } from "@/components/ui/primitives";

export default function Home() {
  const categories = useQuery({ queryKey: ["categories"], queryFn: getCategories });
  const products = useQuery({ queryKey: ["products", "featured"], queryFn: () => getProducts({ sort: "popularity", limit: "8" }) });
  return <>
    <section className="hero overflow-hidden text-white"><div className="shell relative grid gap-10 py-16 lg:grid-cols-[1.08fr_.92fr] lg:py-24">
      <div className="relative z-10 flex flex-col justify-center"><p className="inline-flex w-fit items-center gap-2 rounded-lg border border-white/15 bg-white/10 px-3 py-1.5 text-[11px] font-bold uppercase tracking-[.14em] text-[#63f5c6]"><Sparkles size={14} /> The better everyday edit</p><h1 className="mt-6 max-w-xl text-5xl font-semibold tracking-[-.065em] sm:text-7xl">Find objects with<br /><em className="font-serif font-normal text-[#63f5c6]">a point of view.</em></h1><p className="mt-6 max-w-lg text-lg leading-8 text-slate-300">A modern marketplace for independent makers, practical design, and the pieces that make a space feel entirely yours.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/products" className="btn bg-[#63f5c6] text-slate-950 hover:bg-[#a0ffdc]">Shop the edit <ArrowRight size={17} /></Link><Link href="/categories" className="btn border border-white/20 bg-white/5 text-white hover:bg-white/10">Explore collections</Link></div><div className="mt-12 grid max-w-lg grid-cols-3 gap-4 border-t border-white/15 pt-6 text-sm text-slate-300"><span><b className="block text-2xl text-white">24h</b>dispatch</span><span><b className="block text-2xl text-white">4.9/5</b>community love</span><span><b className="block text-2xl text-white">New</b>every week</span></div></div>
      <div className="relative z-10 min-h-[390px] overflow-hidden rounded-[2rem] border border-white/15 bg-[#151e33]"><span className="hero-orb hero-orb--one" /><span className="hero-orb hero-orb--two" /><span className="hero-orb hero-orb--three" /><div className="hero-tile absolute left-7 top-9 w-56 rounded-[1.5rem] p-5 text-slate-900 sm:left-10 sm:top-12"><BadgeCheck className="text-violet-700" size={22} /><p className="mt-8 text-xs font-bold uppercase tracking-widest text-slate-500">The weekly object</p><p className="mt-2 font-serif text-3xl leading-8">Designed for<br />real life.</p><p className="mt-4 text-sm text-slate-500">Made by sellers who care about the details.</p></div><div className="absolute bottom-8 right-7 flex items-center gap-2 rounded-xl border border-white/15 bg-slate-950/60 px-4 py-2 text-xs font-bold backdrop-blur"><span className="h-2 w-2 rounded-full bg-[#63f5c6]" /> Independent sellers, live now</div></div>
    </div></section>
    <section className="shell py-16"><div className="section-heading"><div><p className="eyebrow">Explore your way</p><h2>Start with a collection.</h2></div><Link href="/categories" className="text-link">All categories <ArrowRight size={16} /></Link></div>{categories.isError ? <ErrorState onRetry={() => categories.refetch()} /> : categories.data?.length ? <CategoryGrid categories={categories.data} /> : <p className="text-slate-500">Categories will appear here once the store is stocked.</p>}</section>
    <section className="border-y border-slate-200 bg-white/65 py-16"><div className="shell"><div className="section-heading"><div><p className="eyebrow">Popular this week</p><h2>The community&apos;s picks.</h2></div><Link href="/products?sort=popularity" className="text-link">View all <ArrowRight size={16} /></Link></div>{products.isLoading ? <div className="grid grid-cols-2 gap-4 sm:grid-cols-4">{Array.from({ length: 4 }, (_, index) => <ProductSkeleton key={index} />)}</div> : products.data?.products.length ? <ProductGrid products={products.data.products} /> : <p className="text-slate-500">No products are live yet.</p>}</div></section>
    <section className="shell py-16"><div className="grid overflow-hidden rounded-[2rem] bg-violet-600 text-white md:grid-cols-2"><div className="p-9 sm:p-14"><p className="eyebrow text-[#b7ffdf]">A store worth returning to</p><h2 className="mt-4 max-w-md font-serif text-4xl leading-none">Thoughtful pieces. Independent people.</h2><p className="mt-5 max-w-md text-violet-100">Discover products from makers and sellers who put usefulness, quality, and character first.</p><Link className="btn mt-8 bg-[#63f5c6] text-slate-950 hover:bg-[#a0ffdc]" href="/products"><Boxes size={17} /> Browse everything</Link></div><div className="min-h-64 bg-[radial-gradient(circle_at_28%_35%,#63f5c6_0,transparent_18%),radial-gradient(circle_at_74%_67%,#ffbc6a_0,transparent_24%),#121b35]" /></div></section>
    <section className="shell grid gap-6 border-t border-slate-200 py-10 sm:grid-cols-3">{[[Truck, "Fast, thoughtful delivery", "Free delivery on qualifying orders."], [Undo2, "Easy returns", "Fourteen days to change your mind."], [ShieldCheck, "Checkout with confidence", "Protected payments and verified sellers."]].map(([Icon, title, copy]) => { const Item = Icon as typeof Truck; return <div key={String(title)} className="flex gap-4"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-violet-100 text-violet-700"><Item size={19} /></span><div><h3 className="font-semibold">{String(title)}</h3><p className="mt-1 text-sm text-slate-500">{String(copy)}</p></div></div>; })}</section>
  </>;
}
