"use client";

import Link from "next/link";
import { ArrowRight, Boxes, Check, ShieldCheck, Sparkles, Star, Truck, Undo2 } from "lucide-react";
import { useQuery } from "@tanstack/react-query";
import { getCategories, getProducts } from "@/services/catalog";
import { CategoryGrid, ProductGrid } from "@/components/products/catalog";
import { ProductSkeleton } from "@/components/ui/product-skeleton";
import { ErrorState } from "@/components/ui/primitives";

export default function Home() {
  const categories = useQuery({ queryKey: ["categories"], queryFn: getCategories });
  const products = useQuery({ queryKey: ["products", "featured"], queryFn: () => getProducts({ sort: "popularity", limit: "8" }) });
  return <>
    <section className="border-b border-slate-200 bg-white"><div className="shell grid gap-10 py-12 lg:grid-cols-[1.08fr_.92fr] lg:py-20"><div className="flex flex-col justify-center"><p className="inline-flex w-fit items-center gap-2 rounded-full bg-violet-50 px-3 py-1.5 text-[11px] font-bold uppercase tracking-[.13em] text-violet-700"><Sparkles size={14} /> The considered marketplace</p><h1 className="mt-6 max-w-2xl font-serif text-5xl leading-[.95] tracking-[-.065em] text-slate-950 sm:text-7xl">Useful objects.<br /><span className="text-violet-600">Beautifully chosen.</span></h1><p className="mt-6 max-w-lg text-base leading-7 text-slate-600 sm:text-lg">Find everyday pieces from independent sellers who care about material, function, and the small details that matter.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/products" className="btn btn-dark">Shop all products <ArrowRight size={17} /></Link><Link href="/categories" className="btn btn-light">Explore categories</Link></div><div className="mt-10 flex flex-wrap gap-x-6 gap-y-3 text-sm text-slate-600"><span className="inline-flex items-center gap-2"><Check size={16} className="text-teal-600" /> Curated sellers</span><span className="inline-flex items-center gap-2"><Check size={16} className="text-teal-600" /> Secure checkout</span><span className="inline-flex items-center gap-2"><Check size={16} className="text-teal-600" /> Easy returns</span></div></div>
      <div className="relative min-h-[390px] overflow-hidden rounded-2xl bg-slate-950 p-5 sm:p-7"><div className="absolute inset-0 bg-[radial-gradient(circle_at_15%_20%,rgb(20_184_166_/_0.38),transparent_23%),radial-gradient(circle_at_84%_72%,rgb(79_70_229_/_0.7),transparent_32%)]" /><div className="relative flex h-full flex-col justify-between"><div className="flex items-center justify-between text-xs font-bold uppercase tracking-[.14em] text-slate-300"><span>Independent design</span><span className="rounded-full border border-white/15 px-3 py-1.5 text-teal-200">New this week</span></div><div className="grid gap-3 sm:grid-cols-[1.1fr_.9fr]"><article className="rounded-xl bg-white p-5 text-slate-950 shadow-xl"><p className="text-xs font-bold uppercase tracking-[.13em] text-violet-700">Morrow edit</p><p className="mt-8 font-serif text-4xl leading-none tracking-[-.05em]">Made to earn<br />its place.</p><p className="mt-4 text-sm leading-6 text-slate-500">Thoughtful pieces for homes, desks, and days in motion.</p></article><div className="flex flex-col justify-end gap-3"><div className="rounded-xl border border-white/15 bg-white/10 p-4 backdrop-blur"><div className="flex items-center gap-1 text-teal-300">{Array.from({ length: 5 }, (_, index) => <Star key={index} size={14} className="fill-current" />)}</div><p className="mt-3 text-sm font-semibold text-white">Loved by everyday collectors</p></div><div className="rounded-xl bg-teal-300 p-4 text-slate-950"><p className="text-xs font-bold uppercase tracking-[.13em]">Just landed</p><p className="mt-1 font-serif text-2xl leading-none">Fresh finds, weekly.</p></div></div></div></div></div>
    </div></section>
    <section className="shell py-16"><div className="section-heading"><div><p className="eyebrow">Shop by feeling</p><h2>Start with a category.</h2></div><Link href="/categories" className="text-link">View all categories <ArrowRight size={16} /></Link></div>{categories.isError ? <ErrorState onRetry={() => categories.refetch()} /> : categories.data?.length ? <CategoryGrid categories={categories.data} /> : <p className="text-slate-500">Categories will appear here once the store is stocked.</p>}</section>
    <section className="border-y border-slate-200 bg-slate-50 py-16"><div className="shell"><div className="section-heading"><div><p className="eyebrow">Popular right now</p><h2>Most saved this week.</h2></div><Link href="/products?sort=popularity" className="text-link">Browse all <ArrowRight size={16} /></Link></div>{products.isLoading ? <div className="grid grid-cols-2 gap-4 sm:grid-cols-4">{Array.from({ length: 4 }, (_, index) => <ProductSkeleton key={index} />)}</div> : products.data?.products.length ? <ProductGrid products={products.data.products} /> : <p className="text-slate-500">No products are live yet.</p>}</div></section>
    <section className="shell grid gap-5 py-12 sm:grid-cols-3">{[[Truck, "Thoughtful delivery", "Free delivery on qualifying orders."], [Undo2, "Easy returns", "Fourteen days to change your mind."], [ShieldCheck, "Shop with confidence", "Protected payments and verified sellers."]].map(([Icon, title, copy]) => { const Item = Icon as typeof Truck; return <article key={String(title)} className="card p-5"><span className="grid h-10 w-10 place-items-center rounded-lg bg-violet-50 text-violet-700"><Item size={19} /></span><h3 className="mt-6 font-serif text-2xl">{String(title)}</h3><p className="mt-2 text-sm leading-6 text-slate-500">{String(copy)}</p></article>; })}</section>
    <section className="shell pb-6"><div className="flex flex-col justify-between gap-6 rounded-2xl bg-violet-600 p-7 text-white sm:flex-row sm:items-end sm:p-10"><div><p className="text-xs font-bold uppercase tracking-[.14em] text-teal-200">For curious shoppers</p><h2 className="mt-3 max-w-xl font-serif text-4xl leading-none tracking-[-.045em]">A better place to find everyday essentials.</h2></div><Link className="btn w-fit bg-white text-violet-700 hover:bg-violet-50" href="/products"><Boxes size={17} /> Explore the marketplace</Link></div></section>
  </>;
}
